name: Build and release Apk

on: push

#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
      - name: build prod
        run: |
          flutter pub get
          flutter test
          flutter build apk --release --flavor dev
           steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get commit hash
      if: ${{ always() }}
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      id: slug
    - name: Chat Setup
      if: ${{ always() }}
      uses: DTherHtun/google-chat-action@v0.8
      with:
        project: ${{ github.repository }}
        commit: ${{ steps.slug.outputs.sha8 }}
        branch: ${{ github.ref }}
        status: ${{ job.status }}
        actionid: ${{ github.repository }}/runs/${{ github.run_id }}
        webhook: "https://chat.googleapis.com/v1/spaces/5buk74AAAAE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=q4y249Z9d3BLuU9JNau5j5_R1HbaRxdvbvffhISmMZw%3D"
      # - name: Prod release
      #   uses: rnkdsh/action-upload-diawi@v1.2.6
      #   with:
      #     token: ${{ secrets.buildApp}}
      #     file: build/app/outputs/flutter-apk/app-dev-release.apk

          
